In [2]:
#import libraries
import sys
from os.path import dirname, join as pjoin
import random
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as sio
import scipy.linalg as la
np.set_printoptions(threshold=1000)

In [3]:
#load usps data into arr
usps_data_dir= "usps_all.mat"
usps_data = sio.loadmat(usps_data_dir)
arr = usps_data['fea']
labels = usps_data['gnd']
arr.shape

(9298, 256)

In [4]:
#shift points to origin
#mean = np.mean(arr, axis =0)
#arr = arr - mean

In [5]:
# Split-out dataset into training and validation
from sklearn.model_selection import train_test_split
X = arr[:,0:255]
y = labels[:,0]
X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=2007, random_state=1)

In [109]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='gini', max_depth=none,max_features=16)
clf.fit(X_train,Y_train)

NameError: name 'none' is not defined

In [107]:
#Predicting labels on the test set.
y_pred =  clf.predict(X_validation)

In [108]:
from sklearn.metrics import accuracy_score
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=clf.predict(X_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_validation, y_pred=y_pred))

Accuracy Score on train data:  1.0
Accuracy Score on test data:  0.8604882909815645


In [88]:
text_representation = tree.export_text(clf)
print(text_representation)

|--- feature_194 <= -1.00
|   |--- feature_142 <= -1.00
|   |   |--- feature_34 <= -1.00
|   |   |   |--- feature_167 <= 0.07
|   |   |   |   |--- feature_66 <= -1.00
|   |   |   |   |   |--- feature_182 <= -0.35
|   |   |   |   |   |   |--- feature_39 <= -0.67
|   |   |   |   |   |   |   |--- feature_92 <= -0.99
|   |   |   |   |   |   |   |   |--- class: 4
|   |   |   |   |   |   |   |--- feature_92 >  -0.99
|   |   |   |   |   |   |   |   |--- class: 5
|   |   |   |   |   |   |--- feature_39 >  -0.67
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |--- feature_182 >  -0.35
|   |   |   |   |   |   |--- feature_244 <= -1.00
|   |   |   |   |   |   |   |--- feature_229 <= -0.99
|   |   |   |   |   |   |   |   |--- class: 5
|   |   |   |   |   |   |   |--- feature_229 >  -0.99
|   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- feature_244 >  -1.00
|   |   |   |   |   |   |   |--- feature_59 <= -0.99
|   |   |   |   |   |   |   |   |--- class: 7
|   

In [99]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
#Evaluate Predictions
print(accuracy_score(Y_validation, y_pred))
print(confusion_matrix(Y_validation, y_pred))

0.6995515695067265
[[278   0  24  15   0   0   9   9   2   1]
 [  0 260   0   0   0   0  12   0   3   0]
 [  1   2 125  39   3   0  20   4   8   0]
 [  6   3  31 130   1   0   5  11   1   3]
 [  1   6   5   6 130   0   9   5   2   7]
 [ 23   2   3  86   6   0  32   3   8   5]
 [ 13   0  16  13   0   0 113   1   0   0]
 [  0   7   1   3   7   0   0 153   8   4]
 [  3   2  17  32   4   0   8   1  77  12]
 [  0   4   0   2  15   0   0   8   0 138]]


In [142]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [143]:
#Predicting labels on the test set.
y_pred =  neigh.predict(X_validation)

In [141]:
from sklearn.metrics import accuracy_score
print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=neigh.predict(X_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_validation, y_pred=y_pred))

Accuracy Score on train data:  1.0
Accuracy Score on test data:  0.9750871948181365


In [153]:
from sklearn.svm import SVC
clm = SVC()
clm.fit(X, y)

SVC()

In [154]:
#Predicting labels on the test set.
y_pred =  clm.predict(X_validation)

In [155]:

print('Accuracy Score on train data: ', accuracy_score(y_true=Y_train, y_pred=clm.predict(X_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=Y_validation, y_pred=y_pred))

Accuracy Score on train data:  0.9884789466465506
Accuracy Score on test data:  0.987045341305431
